@rooturl = http://localhost:3000

### Auth
# @name signUp
POST {{rooturl}}/auth/signup
Content-Type: application/json

{
	"username": "nascarsayan",
	"password": "Yukino#8man"
}

###
# @name signIn
POST {{rooturl}}/auth/signin
Content-Type: application/json

{
	"username": "nascarsayan",
	"password": "Yukino#8man"
}

###
@token = {{signIn.response.body.$.accessToken}}
###
GET {{rooturl}}/tasks
	?dummy=dummy
	# &status=DONE
	# &search=busi
Authorization: Bearer {{token}}

###
# @name createTask
POST {{rooturl}}/tasks
Authorization: Bearer {{token}}
Content-Type: application/json

{
	"title": "Create A Progressive Web App",
	"description": "Innovate a classy business idea"
}
###
@taskId = {{createTask.response.body.$.id}}
###
GET {{rooturl}}/tasks/{{taskId}}
Authorization: Bearer {{token}}
###
PATCH {{rooturl}}/tasks/{{taskId}}/status
Authorization: Bearer {{token}}
Content-Type: application/json

{
	"status": "done"
}
###
DELETE {{rooturl}}/tasks/{{taskId}}

### Auth
# @name signIn
POST {{rooturl}}/auth/signin
Content-Type: application/json

{
	"username": "nascarsayan",
	"password": "Yukino#8man"
}

###
@token = {{signIn.response.body.$.accessToken}}
###
POST {{rooturl}}/auth/test
Authorization: Bearer {{token}}
